In [2]:
import pandas as pd

ratings = pd.read_csv(
    r"D:\Placement Prediction system\data\ratings.csv",
    sep="::",
    engine="python",
    header=None,
    names=["user_id", "movie_id", "rating", "timestamp"]
)

ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [3]:
print("Dataset shape:", ratings.shape)
print("\nColumn names:")
print(ratings.columns.tolist())

Dataset shape: (1000209, 4)

Column names:
['user_id', 'movie_id', 'rating', 'timestamp']

In [5]:
ratings.isnull().sum()

user_id      0
movie_id     0
rating       0
timestamp    0
dtype: int64

In [6]:
ratings.duplicated().sum()

np.int64(0)

In [7]:
print("Missing values: ")
print(ratings.isnull().sum())

print("\nDuplicate rows: ")
print(ratings.duplicated().sum())

Missing values:
user_id      0
movie_id     0
rating       0
timestamp    0
dtype: int64

Duplicate rows:
0

In [8]:
print(ratings["rating"].value_counts().sort_index())

rating
1     56174
2    107557
3    261197
4    348971
5    226310
Name: count, dtype: int64

In [9]:
print("Number of users:", ratings["user_id"].nunique())
print("Number of movies:", ratings["movie_id"].nunique())
print("Number of ratings:", len(ratings))

Number of users: 6040
Number of movies: 3706
Number of ratings: 1000209

In [10]:
ratings.describe()

            user_id      movie_id        rating     timestamp
count  1.000209e+06  1.000209e+06  1.000209e+06  1.000209e+06
mean   3.024512e+03  1.865540e+03  3.581564e+00  9.722437e+08
std    1.728413e+03  1.096041e+03  1.117102e+00  1.215256e+07
min    1.000000e+00  1.000000e+00  1.000000e+00  9.567039e+08
25%    1.506000e+03  1.030000e+03  3.000000e+00  9.653026e+08
50%    3.070000e+03  1.835000e+03  4.000000e+00  9.730180e+08
75%    4.476000e+03  2.770000e+03  4.000000e+00  9.752209e+08
max    6.040000e+03  3.952000e+03  5.000000e+00  1.046455e+09

In [13]:
import pandas as pd

movies = pd.read_csv(
    r"D:\Placement Prediction system\data\movies.csv",
    sep="::",
    engine="python",
    header=None,
    names=["movie_id", "title", "genres"],
    encoding="latin-1"
)

movies.head()

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [14]:
print("Number of movies:", movies.shape[0])
print(movies.columns.tolist())

Number of movies: 3883
['movie_id', 'title', 'genres']

In [ ]:
movie_ratings = pd.merge(
    ratings,
    movies,
    on="movie_id"
)

movie_ratings.head()

,user_id,movie_id,rating,timestamp,title,genres
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance
3,1,3408,4,978300275,Erin Brockovich (2000),Drama
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy

: